name: UVLoadedChunks
main: net.uvnode.uvloadedchunks.UVLoadedChunks
version: 1.0.0
load: POSTWORLD
author: jcornwellshiel
website: uv-node.net
softdepend: [dynmap, pluginmetrics]

commands:
  uvloadedchunks:
    description: Reports on loaded chunks
    usage: /uvloadedchunks
